name: Bryan Kennard
favicon: null
layout_spectrum: 0.8991
typography_spectrum: 0.161
title: Kennard Music
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080000'
    - '#fc9792'
    - '#f4d1c6'
    - '#900417'
    - '#5c3650'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
